# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: Swift
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/JVParallax.xcworkspace # path to your xcodeproj folder
xcode_scheme: JVParallax-Example
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone 5s
script:
- xcodebuild -workspace Example/JVParallax.xcworkspace -scheme JVParallax-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
